# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cadde4729d1e38b0020ff2fb1df8a8016737fd35c323bf400ccf29208c321d17e9202f8cf7667aba7cbf4666aefc69ff0f1fd0a3b7fbfec0c92f0462a8beaf5e

test:
  secret_key_base: c4808a6fe3589d5ea0590c44cf561a6550d509c4763519de2423b53a104d56c3b8d0d76fc98525cd007e4512b98936eb4b6594a901a3787456e0c5d806f7d62d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
